### ISSUE TITLE
Default branch alternatives

### ISSUE THREAD

**Issue by davidlehn** [digitalbazaar/publish-script#24]
We have one package that is using "main" as the default branch.  The branch check defaults should likely accept both "master" and "main" (or whatever name the git community might decide to use by default).

**Comment by mattcollier** [comment]
More packages now, this is becoming a priority.  Meanwhile, it is possible to use the existing code by doing:
```
pubnpm minor -b main
```

**Comment by davidlehn** [comment]
Closing this. Default was changed to `main` to match current best practice.  There is a branch flag to be explicit if needed. Supporting multiple defaults seems difficult and very error prone with little benefit going forward.
